flowchart LR
  actor_actor_user["&laquo;Actor&raquo;<br/>用户（徒步者）"]
  subgraph system_context_trail_mate_system["Trail Mate 系统"]
    subgraph system_context_contact_module["联系人管理"]
      useCase_use_case_browse_contacts(["浏览联系人"])
    end
  end
  actor_actor_user --- useCase_use_case_browse_contacts
