flowchart LR
  actor_actor_actor_user["&laquo;Actor&raquo;<br/>actor:user"]
  subgraph system_context_item_ajfw3y["位置追踪"]
    useCase_use_case_item_qp99mz(["浏览追踪记录"])
  end
  actor_actor_actor_user --- useCase_use_case_item_qp99mz
