flowchart LR
  actor_actor_outdoor_user["&laquo;Actor&raquo;<br/>户外用户"]
  actor_actor_other_mesh_node["&laquo;Actor&raquo;<br/>其他网格节点"]
  external_external_system_mesh_network["&laquo;External System&raquo;<br/>网格网络"]
  subgraph system_context_trail_mate_system["Trail Mate 户外通信与导航系统"]
    subgraph system_context_chat_communication["聊天通信"]
      useCase_use_case_send_text_message(["发送文字消息"])
      useCase_use_case_receive_text_message(["接收并查看聊天消息"])
    end
  end
  actor_actor_outdoor_user --- useCase_use_case_send_text_message
  external_external_system_mesh_network --- useCase_use_case_send_text_message
  actor_actor_outdoor_user --- useCase_use_case_receive_text_message
  actor_actor_other_mesh_node --- useCase_use_case_receive_text_message
  external_external_system_mesh_network --- useCase_use_case_receive_text_message
