flowchart LR
  actor_actor_hiker["&laquo;Actor&raquo;<br/>徒步者"]
  subgraph system_context_trail_mate_system["Trail Mate 系统"]
    subgraph system_context_map["地图与导航"]
      useCase_use_case_browse_map(["浏览地图"])
    end
  end
  actor_actor_hiker --- useCase_use_case_browse_map
