flowchart LR
  actor_actor_actor_user["&laquo;Actor&raquo;<br/>actor:user"]
  subgraph system_context_item_gqhdko["能源管理"]
    useCase_use_case_item_5hhr9g(["查看能源状态"])
  end
  actor_actor_actor_user --- useCase_use_case_item_5hhr9g
