#!/usr/bin/env python3
"""Generate Trail Mate's compiled-in categorized emoji table and binfont header.

The JSON manifest is the human-reviewed catalogue.  This tool validates its
semantic inventory before emitting a mechanically generated C++ header:

* exactly the manifest-declared number of unique emoji candidates;
* category counts agree with the manifest contract;
* every required Unicode codepoint exists in the source Noto Emoji font;
* the supplied LVGL binfont is embedded byte-for-byte.

The generated header is intentionally not hand-edited.  Run this after
regenerating the matching binfont with generate_binfont_with_lv_font_conv.py.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from fontTools.ttLib import TTFont


IGNORABLE_CODEPOINTS = {0x200D, *range(0xFE00, 0xFE10)}


def cpp_string(value: str) -> str:
    """Return a UTF-8-preserving C++ string literal."""

    return json.dumps(value, ensure_ascii=False)


def font_codepoints(font_path: Path) -> set[int]:
    font = TTFont(font_path)
    return set().union(*(table.cmap.keys() for table in font["cmap"].tables))


def validate_manifest(manifest: dict, font_path: Path) -> list[dict]:
    expected_total = manifest.get("expected_total")
    categories = manifest.get("categories")
    if not isinstance(expected_total, int) or expected_total <= 0:
        raise ValueError("manifest must define a positive expected_total")
    if not isinstance(categories, list) or not categories:
        raise ValueError("manifest must contain a non-empty categories array")

    supported = font_codepoints(font_path)
    seen_ids: set[str] = set()
    seen_candidates: set[str] = set()
    missing_codepoints: dict[str, list[str]] = {}
    total = 0

    for category in categories:
        category_id = category.get("id")
        title = category.get("title")
        icon = category.get("icon")
        candidates = category.get("candidates")
        expected_count = category.get("expected_count")
        if not isinstance(category_id, str) or not category_id:
            raise ValueError("every category must define a non-empty id")
        if category_id in seen_ids:
            raise ValueError(f"duplicate category id: {category_id}")
        seen_ids.add(category_id)
        if not isinstance(title, str) or not title:
            raise ValueError(f"category {category_id} must define a title")
        if not isinstance(icon, str) or not icon:
            raise ValueError(f"category {category_id} must define an icon")
        if not isinstance(candidates, list) or not all(isinstance(value, str) and value for value in candidates):
            raise ValueError(f"category {category_id} has an invalid candidates array")
        if expected_count != len(candidates):
            raise ValueError(
                f"category {category_id} expected {expected_count} candidates, found {len(candidates)}"
            )
        if icon not in candidates:
            raise ValueError(f"category {category_id} icon must also be one of its candidates")

        total += len(candidates)
        for candidate in candidates:
            if candidate in seen_candidates:
                raise ValueError(f"duplicate emoji candidate: {candidate}")
            seen_candidates.add(candidate)
            missing = [
                f"U+{codepoint:04X}"
                for codepoint in map(ord, candidate)
                if codepoint not in IGNORABLE_CODEPOINTS and codepoint not in supported
            ]
            if missing:
                missing_codepoints[candidate] = missing

    if total != expected_total:
        raise ValueError(f"expected exactly {expected_total} candidates, found {total}")
    if missing_codepoints:
        details = "; ".join(
            f"{candidate}: {', '.join(codepoints)}"
            for candidate, codepoints in missing_codepoints.items()
        )
        raise ValueError(f"source font lacks required glyphs: {details}")
    return categories


def render_header(categories: list[dict], font_bytes: bytes) -> str:
    lines = [
        "#pragma once",
        "",
        "// Generated by tools/generate_builtin_emoji_data.py; do not edit by hand.",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "#include \"ui/widgets/text_candidate_data.h\"",
        "",
        "namespace ui::widgets::text_candidate_data",
        "{",
        "",
        "static constexpr const char* kEmojiCandidates[] = {",
    ]

    flattened: list[str] = []
    for category in categories:
        flattened.extend(category["candidates"])
    lines.extend(f"    {cpp_string(candidate)}," for candidate in flattened)
    lines.extend(
        [
            "};",
            "",
            "static constexpr std::size_t kEmojiCandidateCount =",
            "    sizeof(kEmojiCandidates) / sizeof(kEmojiCandidates[0]);",
            "",
            "static constexpr ::ui::widgets::text_candidates::EmojiCategoryInfo kEmojiCategories[] = {",
        ]
    )

    offset = 0
    for category in categories:
        count = len(category["candidates"])
        lines.append(
            "    {"
            f"{cpp_string(category['id'])}, "
            f"{cpp_string(category['title'])}, "
            f"{cpp_string(category['icon'])}, "
            f"{offset}U, {count}U"
            "},"
        )
        offset += count
    lines.extend(
        [
            "};",
            "",
            "static constexpr std::size_t kEmojiCategoryCount =",
            "    sizeof(kEmojiCategories) / sizeof(kEmojiCategories[0]);",
            "",
            "alignas(4) static const std::uint8_t kEmojiCoreBinfont[] = {",
        ]
    )
    for offset in range(0, len(font_bytes), 12):
        chunk = font_bytes[offset : offset + 12]
        lines.append("    " + ", ".join(f"0x{value:02X}" for value in chunk) + ",")
    lines.extend(
        [
            "};",
            "",
            "static constexpr std::size_t kEmojiCoreBinfontSize =",
            "    sizeof(kEmojiCoreBinfont);",
            "",
            "} // namespace ui::widgets::text_candidate_data",
            "",
        ]
    )
    return "\n".join(lines)


def render_charset(categories: list[dict]) -> str:
    """Preserve candidate order while emitting each source codepoint once."""

    seen: set[str] = set()
    ordered: list[str] = []
    for category in categories:
        for candidate in category["candidates"]:
            for character in candidate:
                if character not in seen:
                    seen.add(character)
                    ordered.append(character)
    return "".join(ordered) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the categorized builtin emoji C++ header.")
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--font", type=Path, required=True)
    parser.add_argument("--charset-output", type=Path)
    parser.add_argument("--binfont", type=Path)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    manifest_path = args.manifest.resolve()
    font_path = args.font.resolve()
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    categories = validate_manifest(manifest, font_path)

    if args.charset_output:
        charset_path = args.charset_output.resolve()
        charset_path.parent.mkdir(parents=True, exist_ok=True)
        charset_path.write_text(render_charset(categories), encoding="utf-8", newline="\n")
        print(f"charset={charset_path}")

    if args.binfont is None and args.output is None:
        return 0
    if args.binfont is None or args.output is None:
        parser.error("--binfont and --output must be supplied together")

    binfont_path = args.binfont.resolve()
    output_path = args.output.resolve()
    font_bytes = binfont_path.read_bytes()
    if not font_bytes:
        raise ValueError("binfont input is empty")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_header(categories, font_bytes), encoding="utf-8", newline="\n")
    candidate_count = sum(len(category["candidates"]) for category in categories)
    print(f"manifest={manifest_path}")
    print(f"categories={len(categories)}")
    print(f"candidates={candidate_count}")
    print(f"binfont_bytes={len(font_bytes)}")
    print(f"output={output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
